name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: install modules
        run: npm i
      - name: linting
        run: npm run eslint
      - name: deploy-to-heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "food-inf-iiigygyiii"
          heroku_email: "saritamar0810@gmail.com"
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !(contains(github.event.commits[0].message, '#skip')) }}
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
